import './components/accordion'
import './components/popular-schools'
import './components/validation'
import './components/range-slider'
import './components/sort-by'
import './components/toggle-filters'
import './components/search'
